name: Enable Remote Desktop on Linux

on: [push, workflow_dispatch]

jobs:
  enable-remote-desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Update and install ngrok dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip
        shell: bash

      - name: Download and extract ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip
          unzip ngrok.zip
          chmod +x ngrok
          sudo mv ngrok /usr/local/bin/
        shell: bash

      - name: Authenticate with ngrok
        run: |
          ngrok authtoken $NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        shell: bash

      - name: Create Tunnel with ngrok
        run: |
          ngrok tcp 3389
        shell: bash
