name: Create ngrok Tunnel for Remote Desktop

on: [push, workflow_dispatch]

jobs:
  create-ngrok-tunnel:
    runs-on: self-hosted
    steps:
      - name: Install ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip
          unzip ngrok.zip
          chmod +x ngrok
          sudo mv ngrok /usr/local/bin/
        shell: bash

      - name: Authenticate with ngrok
        run: |
          ngrok authtoken $NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        shell: bash

      - name: Create Tunnel with ngrok
        run: |
          ngrok tcp 3389
        shell: bash
