name: Enable Remote Desktop

on: [push, workflow_dispatch]

jobs:
  enable-remote-desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Install Ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip
          unzip ngrok.zip
          chmod +x ngrok
          sudo mv ngrok /usr/local/bin/
        shell: bash

      - name: Set Ngrok Authtoken
        run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        shell: bash

      - name: Enable Remote Desktop
        run: |
          sudo apt-get update
          sudo apt-get install -y xrdp

          # Open RDP port in the firewall
          sudo ufw allow 3389/tcp

          # Start the xrdp service
          sudo systemctl start xrdp
        shell: bash

      - name: Create Local User
        run: |
          sudo useradd -m runneradmin1
          sudo echo "runneradmin:password" | sudo chpasswd
          sudo usermod --shell /bin/bash runneradmin
        shell: bash

      - name: Create Tunnel with Ngrok
        run: |
          ngrok tcp 3389
        shell: bash
