name: Enable Remote Desktop on Kali Linux

on: [push, workflow_dispatch]

jobs:
  enable-remote-desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Update and install ngrok dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip
        shell: bash

      - name: Download ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip
          unzip ngrok.zip
        shell: bash

      - name: Authenticate with ngrok
        run: |
          ./ngrok/ngrok authtoken $NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        shell: bash

      - name: Create Tunnel with ngrok
        run: |
          ./ngrok/ngrok tcp 3389
        shell: bash

      - name: Enable Remote Desktop
        run: |
          sudo apt install -y xrdp
          sudo service xrdp start
        shell: bash
