name: Enable Remote Desktop with Xfce

on: [push, workflow_dispatch]

jobs:
  enable-remote-desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Install Ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip
          unzip ngrok.zip
          chmod +x ngrok
          sudo mv ngrok /usr/local/bin/
        shell: bash

      - name: Set Ngrok Authtoken
        run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        shell: bash

      - name: Install Xfce Desktop Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xubuntu-icon-theme xfce4-terminal
        shell: bash

      - name: Install xrdp
        run: |
          sudo apt-get install -y xrdp
        shell: bash

      - name: Open RDP Port in the Firewall
        run: |
          sudo ufw allow 3389/tcp
        shell: bash

      - name: Start the xrdp Service
        run: |
          sudo systemctl start xrdp
        shell: bash

      - name: Create Local User
        run: |
          sudo useradd -m runneradmin1
          sudo echo "runneradmin1:password" | sudo chpasswd
          sudo usermod --shell /bin/bash runneradmin1
        shell: bash

      - name: Set Xfce Session
        run: |
          echo "xfce4-session" > /home/runneradmin1/.xsession
        shell: bash

      - name: Create Tunnel with Ngrok
        run: |
          ngrok tcp 3389
        shell: bash
